name: Generate ASCII Artwork

on: push

jobs:
  generate_ascii_artwork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    # Method -1: 
    #   - name: Install Cowsay program
    #     run: sudo apt-get update && sudo apt-get install -y cowsay

    #   - name: Generate ASCII artwork
    #     run: cowsay -f dragon "Run for cover, I am a dragon!" >> dragon_artwork.txt

    #   - name: Test the file existence
    #     run: |
    #       if [ -f dragon_artwork.txt ]; then
    #         echo "File exists."
    #         grep -i "dragon" dragon_artwork.txt
    #       else
    #         echo "File does not exist."
    #       fi
    #   - name: Display ASCII artwork
    #     run: cat dragon_artwork.txt

    #   - name: Checkout repo files
    #     run: ls -ltar

    # Method -2: 
      - name: Run ASCII artwork shell script
        run: .github/workflows/ascii_shellscrpir.sh
